=== huongdanjavacom/abeille/src/main/java/com/jeta/swingbuilder/config/abeille_beans.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:element name="abeillebuilder">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="beans" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="version" use="required" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="beans">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="bean" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="bean">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ctor" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="properties" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="id" use="required" type="xs:string" />
			<xs:attribute name="class" use="optional" type="xs:string" />
			<xs:attribute name="description" use="optional"
				type="xs:string" />
			<xs:attribute name="icon" use="optional" type="xs:string" />
            <xs:attribute name="scrollable" type="xs:boolean" use="optional"></xs:attribute>
            <xs:attribute name="ref" use="optional" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="ctor">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="parm" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="factory" use="optional" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="parm">
		<xs:complexType>
			<xs:attribute name="index" use="required" type="xs:int" />
			<xs:attribute name="class" use="required" type="xs:string" />			<xs:attribute name="value" use="required" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="properties">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="property"
					minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="property">
		<xs:complexType>
			<xs:attribute name="name" use="required" type="xs:string" />
			<xs:attribute name="value" use="optional" type="xs:string" />
			<xs:attribute name="codeonly" type="xs:boolean" use="optional" />
			<xs:attribute name="write" type="xs:boolean" use="optional" />
			<xs:attribute name="editor" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>

</xs:schema>

=== huongdanjavacom/abeille/src/main/java/com/jeta/sample/SampleBeans.xml
<?xml version="1.0" encoding="UTF-8"?>
<abeillebuilder version="3.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="abeille_beans.xsd">
	<beans>
		<bean id="jlabel" class="javax.swing.JLabel" description="JLabel" icon="forms/16x16/palette_label16.gif" scrollable="false">
			<properties>
				<property name="text" value="Test" write="true" />
				<property name="opaque" write="true" />
				<property name="taborder@Integer" value="1" write="true" />
				<property name="binding@String" value="person.name=text;" />
				<property name="test@Color" value="192,192,192" codeonly="true" write="true" editor="com.jeta.sample.SampleColorEditor" />
				<property name="test@Long" value="12" codeonly="true" write="true" />
				<property name="test@Float" value="12.9" codeonly="true" write="true" />
				<property name="test@Double" value="12.34" codeonly="true" write="true" />
				<property name="test@Boolean" value="false" codeonly="true" write="true" />
				<property name="test@Font" value="Arial,0,16" codeonly="true" write="true" />
				<property name="test@List" value="AA|AA|BB|CC|DD" codeonly="true" write="true" />
				<property name="test@Option" value="1|1|AA|2|BB|3|CC|4|DD" codeonly="true" write="true" />
			</properties>
		</bean>
		<bean id="jlabel1" description="JLabel1" ref="jlabel">
			<ctor>
				<parm index="0" class="String" value="Test1" />
				<parm index="1" class="Integer" value="0" />
			</ctor>
		</bean>
		<bean id="jlabel2" description="JLabel2" icon="development/16x16/bean.png" ref="jlabel">
			<ctor factory="local.LocalSwingFactory.createJLabel">
			</ctor>
		</bean>
		<bean id="jtextfield" class="javax.swing.JTextField" description="JTextField" icon="forms/16x16/text_field.png" scrollable="false">
			<properties>
				<property name="text" value="Test" write="true" />
				<property name="opaque" write="true" />
				<property name="taborder@Integer" value="1" write="true" />
				<property name="binding@String" value="person.name=text;" />
			</properties>
		</bean>
			</beans>
</abeillebuilder>

=== huongdanjavacom/abeille/src/main/java/com/jeta/swingbuilder/config/abeille_beans.xml
<?xml version="1.0" encoding="UTF-8"?>
<abeillebuilder version="3.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="abeille_beans.xsd">
	<beans>
		<bean id="jlabel" class="javax.swing.JLabel" description="JLabel" icon="forms/16x16/palette_label16.gif" scrollable="false">
			<properties>
				<property name="text" value="Test" write="true" />
				<property name="opaque" write="true" />
				<property name="taborder@Integer" value="1" write="true" />
				<property name="binding@String" value="person.name=text;" />
				<property name="foreground@Color" value="192,192,192" codeonly="true" write="true" editor="com.jeta.sample.SampleColorEditor" />
				<property name="test_color@Color" value="192,192,192" codeonly="true" write="true" />
			</properties>
		</bean>
		<bean id="jlabel1" description="JLabel1" ref="jlabel">
			<ctor>
				<parm index="0" class="String" value="Test1" />
				<parm index="1" class="Integer" value="0" />
			</ctor>
		</bean>
		<bean id="jlabel2" description="JLabel2" icon="development/16x16/bean.png" ref="jlabel">
			<ctor factory="local.LocalSwingFactory.createJLabel">
			</ctor>
		</bean>
		<bean id="jtextfield" class="javax.swing.JTextField" description="JTextField" icon="forms/16x16/text_field.png" scrollable="false">
			<properties>
				<property name="text" value="Test" write="true" />
				<property name="opaque" write="true" />
				<property name="taborder@Integer" value="1" write="true" />
				<property name="binding@String" value="person.name=text;" />
				<property name="foreground@Color" value="192,192,192" codeonly="true" write="true" />
			</properties>
		</bean>
			</beans>
</abeillebuilder>
