=== huongdanjavacom/abeille/src/main/java/com/jeta/swingbuilder/config/abeille_toolbar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:element name="abeillebuilder">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="toolbar" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="version" use="optional" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="toolbar">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="bar" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="bar">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="item" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="description" use="required" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="item">
		<xs:complexType>
			<xs:attribute name="description" use="optional" type="xs:string" />
			<xs:attribute name="icon" use="optional" type="xs:string" />
			<xs:attribute name="ref" use="required" type="xs:string">
				<xs:annotation>
					<xs:documentation>refrence for bean id</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== huongdanjavacom/abeille/src/main/java/com/jeta/swingbuilder/config/abeille_toolbar.xml
<?xml version="1.0" encoding="UTF-8"?>
<abeillebuilder version="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="abeille_toolbar.xsd">
    <toolbar>
		<bar description="JLabel">
		    <item ref="jlabel"/>
		    <item description="TEST1" ref="jlabel1"/>
		    <item description="TEST2" icon="development/16x16/web_component.png" ref="jlabel2"/>
		    		</bar>
		<bar description="JText">
		    <item ref="jtextfield"/>
		</bar>
	</toolbar>
</abeillebuilder>
